/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVues;

import java.awt.Container;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import pkgEntites.HibernateUtil;

/**
 *
 * @author Maxence
 */
public class jfPrincipal extends javax.swing.JFrame {
        //Declaration et initialisation des sessions
   private  static Session session = HibernateUtil.getSessionFactory().openSession();
   
        //Declaration des panels
   protected jpEtablissementAjout pnlEtablissementAjout = new jpEtablissementAjout();
   protected jpEtablissementConsult pnlEtablissementConsult = new jpEtablissementConsult();
   protected jpTypeChambreAjout pnlTypeChambreAjout = new jpTypeChambreAjout();
   protected jpTypeChambreConsult pnlTypeChambreConsult = new jpTypeChambreConsult();
   protected jpHebergementConsult pnlHebergementConsult = new jpHebergementConsult();
   protected jpAttributionConsult pnlAttributionConsult = new jpAttributionConsult();
   protected jpAccueil pnlAccueil  = new jpAccueil();
  // private Container pnlPrincipal = null;

   public jfPrincipal() {
        initComponents();
        this.setContentPane(pnlAccueil);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbTop = new javax.swing.JMenuBar();
        jmAccueil = new javax.swing.JMenu();
        jmniPropos = new javax.swing.JMenuItem();
        jmniQuitter = new javax.swing.JMenuItem();
        jmEtablissement = new javax.swing.JMenu();
        jmniEtablissementConsulter = new javax.swing.JMenuItem();
        jmniEtablissementAjout = new javax.swing.JMenuItem();
        jmChambres = new javax.swing.JMenu();
        jmniChambresConsulter = new javax.swing.JMenuItem();
        jmniChambresAjout = new javax.swing.JMenuItem();
        jmHebergement = new javax.swing.JMenu();
        jmniHebergementConsulter = new javax.swing.JMenuItem();
        jmAttribution = new javax.swing.JMenu();
        jmniAttributionConsulter = new javax.swing.JMenuItem();
        jmniAttributionAjout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jmAccueil.setText("Accueil");

        jmniPropos.setText("A propos");
        jmniPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniProposActionPerformed(evt);
            }
        });
        jmAccueil.add(jmniPropos);

        jmniQuitter.setText("Quitter");
        jmniQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniQuitterActionPerformed(evt);
            }
        });
        jmAccueil.add(jmniQuitter);

        jmbTop.add(jmAccueil);

        jmEtablissement.setText("Etablissements");

        jmniEtablissementConsulter.setText("Consulter");
        jmniEtablissementConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniEtablissementConsulterActionPerformed(evt);
            }
        });
        jmEtablissement.add(jmniEtablissementConsulter);

        jmniEtablissementAjout.setText("Ajouter");
        jmniEtablissementAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniEtablissementAjoutActionPerformed(evt);
            }
        });
        jmEtablissement.add(jmniEtablissementAjout);

        jmbTop.add(jmEtablissement);

        jmChambres.setText("Chambres");

        jmniChambresConsulter.setText("Consulter");
        jmniChambresConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniChambresConsulterActionPerformed(evt);
            }
        });
        jmChambres.add(jmniChambresConsulter);

        jmniChambresAjout.setText("Ajouter");
        jmniChambresAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniChambresAjoutActionPerformed(evt);
            }
        });
        jmChambres.add(jmniChambresAjout);

        jmbTop.add(jmChambres);

        jmHebergement.setText("Hebergement");

        jmniHebergementConsulter.setText("Consulter");
        jmniHebergementConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniHebergementConsulterActionPerformed(evt);
            }
        });
        jmHebergement.add(jmniHebergementConsulter);

        jmbTop.add(jmHebergement);

        jmAttribution.setText("Attribution");

        jmniAttributionConsulter.setText("Consulter");
        jmniAttributionConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniAttributionConsulterActionPerformed(evt);
            }
        });
        jmAttribution.add(jmniAttributionConsulter);

        jmniAttributionAjout.setText("Ajouter");
        jmAttribution.add(jmniAttributionAjout);

        jmbTop.add(jmAttribution);

        setJMenuBar(jmbTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public static Session getSession(){
        return session;
    }
    
    public static void setSession(Session psession){
        jfPrincipal.session=psession;
    }
        //Fermeture de session, puis de l'application
    private void jmniQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniQuitterActionPerformed
        getSession().close();
        System.exit(0);
    }//GEN-LAST:event_jmniQuitterActionPerformed
        //Affichage du panel permettant de consulter les Etablissements / Chargement des etablissements dans le tableau
    private void jmniEtablissementConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniEtablissementConsulterActionPerformed
        this.setContentPane(pnlEtablissementConsult);
        pnlEtablissementConsult.chargerTable();
        pack();
    }//GEN-LAST:event_jmniEtablissementConsulterActionPerformed
        //Affichage du panel permettant l'ajout d'un etablissement
    private void jmniEtablissementAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniEtablissementAjoutActionPerformed
        this.setContentPane(pnlEtablissementAjout);
        pack();
    }//GEN-LAST:event_jmniEtablissementAjoutActionPerformed
        //Affichage du panel permettant de consulter les types de chambres / Chargement des types de chambres dans le tableau
    private void jmniChambresConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniChambresConsulterActionPerformed
        this.setContentPane(pnlTypeChambreConsult);
        pnlTypeChambreConsult.chargerTable();
        pack();
    }//GEN-LAST:event_jmniChambresConsulterActionPerformed
        //Affichage du panel permettant d'ajouter un type de chambre
    private void jmniChambresAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniChambresAjoutActionPerformed
        this.setContentPane(pnlTypeChambreAjout);
        pack();
    }//GEN-LAST:event_jmniChambresAjoutActionPerformed
        //Affichage du panel permettant de consulter les offres d'hebergements/ Chargement des etablissements dans la liste deroulante
    private void jmniHebergementConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniHebergementConsulterActionPerformed
        this.setContentPane(pnlHebergementConsult);
        pnlHebergementConsult.chargeListe();
        pack();
    }//GEN-LAST:event_jmniHebergementConsulterActionPerformed
        //Affichage du panel permettant de consulter l'attribution des chambres/ Chargement des etablissements et des groupes dans les listes deroulante
    private void jmniAttributionConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniAttributionConsulterActionPerformed
        this.setContentPane(pnlAttributionConsult);
        pnlAttributionConsult.chargeListeEtablissement();
        pnlAttributionConsult.chargeListeGroupe();
        pack();
    }//GEN-LAST:event_jmniAttributionConsulterActionPerformed

    private void jmniProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniProposActionPerformed
         JOptionPane.showMessageDialog(null, "Boisgontier Chloé \nBures Maxence");   // TODO add your handling code here:
    }//GEN-LAST:event_jmniProposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAccueil;
    private javax.swing.JMenu jmAttribution;
    private javax.swing.JMenu jmChambres;
    private javax.swing.JMenu jmEtablissement;
    private javax.swing.JMenu jmHebergement;
    private javax.swing.JMenuBar jmbTop;
    private javax.swing.JMenuItem jmniAttributionAjout;
    private javax.swing.JMenuItem jmniAttributionConsulter;
    private javax.swing.JMenuItem jmniChambresAjout;
    private javax.swing.JMenuItem jmniChambresConsulter;
    private javax.swing.JMenuItem jmniEtablissementAjout;
    private javax.swing.JMenuItem jmniEtablissementConsulter;
    private javax.swing.JMenuItem jmniHebergementConsulter;
    private javax.swing.JMenuItem jmniPropos;
    private javax.swing.JMenuItem jmniQuitter;
    // End of variables declaration//GEN-END:variables
}
