/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVues;

import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import pkgEntites.Attribution;
import pkgEntites.Etablissement;
import pkgEntites.Groupe;
import pkgEntites.Offre;

/**
 *
 * @author Maxence
 */
public class jpAttributionConsult extends javax.swing.JPanel {

    private boolean bCharge = false;
    private boolean bCharge2 = false;
    private String sEtablissementId = "";
    private String sGroupeId = "";
    private String sTestId = "";

    /**
     * Creates new form jpAttributionConsult
     */
    public jpAttributionConsult() {
        initComponents();
    }

    public void chargeListeEtablissement() {
        String sReq = "From Etablissement";
        Query q = jfPrincipal.getSession().createQuery(sReq);
        jcmbEtablissement.removeAllItems();
        Iterator eta = q.iterate();
        while (eta.hasNext()) {
            Etablissement unEtablissement = (Etablissement) eta.next();
            jcmbEtablissement.addItem(unEtablissement.getEtaNom());
        }
        bCharge = true;
    }

    public void chargeListeGroupe() {
        String sReq2 = "From Groupe";
        Query q2 = jfPrincipal.getSession().createQuery(sReq2);
        jcmbGroupe.removeAllItems();
        Iterator grp = q2.iterate();
        while (grp.hasNext()) {
            Groupe unGroupe = (Groupe) grp.next();
            jcmbGroupe.addItem(unGroupe.getGpNom());
        }
        bCharge2 = true;
    }
    
    private void chargeTable(String sEtablissementId, String sGroupeId){
        int nbligne;
        int i;
        nbligne = jTblAttribution.getRowCount();
        if(nbligne > 0)
            {
            for(i=0;i <nbligne; i++){
                ((DefaultTableModel)jTblAttribution.getModel()).removeRow(0);
            }
        String sReq = "FROM Attribution WHERE Att_Etablissement = '"+sEtablissementId+"' AND Att_Groupe = '"+sGroupeId+"' Order by Att_Etablissement, Att_Groupe Asc";
        Query q = jfPrincipal.getSession().createQuery(sReq);
        //q.setParameter(0, sEtablissementId);
        Iterator eta = q.iterate();
        while(eta.hasNext())
            {
            Attribution unAttribution = (Attribution) eta.next();
            ((DefaultTableModel) jTblAttribution.getModel()).addRow(new Object[] {unAttribution.getId().getAttEtablissement(),unAttribution.getId().getAttTypechambre(), unAttribution.getAttNbchambres()});
            }   
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblEtablissement = new javax.swing.JLabel();
        jlblGroupe = new javax.swing.JLabel();
        jcmbEtablissement = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblAttribution = new javax.swing.JTable();
        jlblQuantite = new javax.swing.JLabel();
        jtxtQuantite = new javax.swing.JTextField();
        jbtModifier = new javax.swing.JButton();
        jcmbGroupe = new javax.swing.JComboBox();

        jlblEtablissement.setText("Etablissement");

        jlblGroupe.setText("Groupe");

        jcmbEtablissement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbEtablissement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbEtablissementActionPerformed(evt);
            }
        });

        jTblAttribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Capacité", "Quantité Dispo", "Quantité Prise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblAttribution.getTableHeader().setReorderingAllowed(false);
        jTblAttribution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblAttributionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblAttribution);
        if (jTblAttribution.getColumnModel().getColumnCount() > 0) {
            jTblAttribution.getColumnModel().getColumn(0).setResizable(false);
            jTblAttribution.getColumnModel().getColumn(1).setResizable(false);
            jTblAttribution.getColumnModel().getColumn(2).setResizable(false);
        }

        jlblQuantite.setText("Quantité");

        jbtModifier.setText("Modifier");

        jcmbGroupe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbGroupeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblEtablissement)
                    .addComponent(jlblGroupe))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtModifier)
                    .addComponent(jcmbEtablissement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlblQuantite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEtablissement)
                    .addComponent(jcmbEtablissement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblGroupe)
                    .addComponent(jcmbGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblQuantite)
                    .addComponent(jtxtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtModifier)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(131, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbEtablissementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbEtablissementActionPerformed
        if (bCharge) {
            String sReq = "from Etablissement Where Eta_Nom = ?";
            Query q = jfPrincipal.getSession().createQuery(sReq);
            q.setParameter(0, jcmbEtablissement.getSelectedItem().toString());
            Attribution unAttribution = (Attribution) q.uniqueResult();
          //  sTestId = unAttribution.getAttNbchambres();
           // Etablissement unEtablissement = (Etablissement) q.uniqueResult();
            sTestId = unAttribution.getId().getAttEtablissement();
            //chargeTable(sEtablissementId);
            System.out.println(sTestId);
        }
    }//GEN-LAST:event_jcmbEtablissementActionPerformed

    private void jTblAttributionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblAttributionMouseClicked
        int ligne = jTblAttribution.getSelectedRow();
        Object celluleQuantite = jTblAttribution.getValueAt(ligne, 2);
        Object celluleChambre = jTblAttribution.getValueAt(ligne, 1);
      //  sChambresId = celluleChambre.toString();
        //  jtxtModif.setText(celluleQuantite.toString()); // TODO add your handling code here:
    }//GEN-LAST:event_jTblAttributionMouseClicked

    private void jcmbGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbGroupeActionPerformed
        if (bCharge2) {
            String sReq = "from Groupe Where Gp_Nom = ?";
            Query q = jfPrincipal.getSession().createQuery(sReq);
            q.setParameter(0, jcmbGroupe.getSelectedItem());
            Attribution unAttribution = (Attribution) q.uniqueResult();
            sGroupeId = unAttribution.getId().getAttGroupe();
            //chargeTable(sEtablissementId, sGroupeId);
        }
    }//GEN-LAST:event_jcmbGroupeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblAttribution;
    private javax.swing.JButton jbtModifier;
    private javax.swing.JComboBox jcmbEtablissement;
    private javax.swing.JComboBox jcmbGroupe;
    private javax.swing.JLabel jlblEtablissement;
    private javax.swing.JLabel jlblGroupe;
    private javax.swing.JLabel jlblQuantite;
    private javax.swing.JTextField jtxtQuantite;
    // End of variables declaration//GEN-END:variables
}
