/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVues;

import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Transaction;
import pkgEntites.Etablissement;



/**
 *
 * @author Maxence
 */
public class jpEtablissementConsult extends javax.swing.JPanel {
   

            //Chargement des listes deroulantes
    public jpEtablissementConsult() {
        initComponents();
        jcbccivil.removeAllItems();
        jcbctype.removeAllItems();
        jcbccivil.addItem("Monsieur");
        jcbccivil.addItem("Madame");
        jcbctype.addItem("Ecole Publique");
        jcbctype.addItem("Ecole Privée");
        jcbctype.addItem("Autres");
        jtxtid.disable();
        jtxtcivil.disable();
        jtxttype.disable();
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblconsult = new javax.swing.JLabel();
        jbtnModif = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblconsult = new javax.swing.JTable();
        lblnom = new javax.swing.JLabel();
        jtxtnom = new javax.swing.JTextField();
        jtxtville = new javax.swing.JTextField();
        jtxtcp = new javax.swing.JTextField();
        jcbctype = new javax.swing.JComboBox();
        lbletablissement = new javax.swing.JLabel();
        lblville = new javax.swing.JLabel();
        jtxtadresse = new javax.swing.JTextField();
        jcbccivil = new javax.swing.JComboBox();
        lblcp = new javax.swing.JLabel();
        lblrespnom1 = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        lbladresse = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jtxttelephone = new javax.swing.JTextField();
        lbltelephone = new javax.swing.JLabel();
        lblmail = new javax.swing.JLabel();
        jtxtmail = new javax.swing.JTextField();
        lbltype = new javax.swing.JLabel();
        lblresponsable = new javax.swing.JLabel();
        lblrespnom = new javax.swing.JLabel();
        jtxtrespnom = new javax.swing.JTextField();
        lblrespprenom = new javax.swing.JLabel();
        jtxtrespprenom = new javax.swing.JTextField();
        jbtnSupp = new javax.swing.JButton();
        jtxttype = new javax.swing.JTextField();
        jtxtcivil = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(600, 600));

        lblconsult.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblconsult.setText("Consultation/Modification");

        jbtnModif.setText("Modifier");
        jbtnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));

        tblconsult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Ville", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblconsult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblconsultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblconsult);
        if (tblconsult.getColumnModel().getColumnCount() > 0) {
            tblconsult.getColumnModel().getColumn(0).setResizable(false);
            tblconsult.getColumnModel().getColumn(1).setResizable(false);
            tblconsult.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblconsult.getColumnModel().getColumn(2).setResizable(false);
            tblconsult.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblconsult.getColumnModel().getColumn(3).setResizable(false);
            tblconsult.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        lblnom.setText("Nom");

        jcbctype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbletablissement.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbletablissement.setText("Etablissement");

        lblville.setText("Ville");

        jcbccivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblcp.setText("Code Postal");

        lblrespnom1.setText("Civilité");

        lbladresse.setText("Adresse");

        lblid.setText("Id");

        lbltelephone.setText("Telephone");

        lblmail.setText("Mail");

        lbltype.setText("Type");

        lblresponsable.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblresponsable.setText("Responsable");

        lblrespnom.setText("Nom");

        lblrespprenom.setText("Prenom");

        jbtnSupp.setText("Supprimer");
        jbtnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblconsult)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblid)
                                            .addComponent(lbladresse))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblnom)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtxtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lbltelephone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jtxttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblcp)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtxtcp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37)
                                        .addComponent(lblville)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtville, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbletablissement, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbltype)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(194, 194, 194)
                                                .addComponent(lblmail)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtxtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(jtxttype, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jcbctype, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(lblresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblrespnom1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblrespnom))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtxtrespnom, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblrespprenom)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxtrespprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtxtcivil, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcbccivil, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jbtnModif)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtnSupp))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblconsult, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbletablissement, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblnom)
                        .addComponent(jtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblid)
                        .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladresse)
                    .addComponent(jtxtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcp)
                    .addComponent(jtxtcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblville)
                    .addComponent(jtxtville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelephone)
                    .addComponent(jtxttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmail)
                    .addComponent(jtxtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltype)
                    .addComponent(jtxttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(lblresponsable, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrespnom1)
                    .addComponent(jtxtcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbccivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrespnom)
                    .addComponent(jtxtrespnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrespprenom)
                    .addComponent(jtxtrespprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnModif)
                    .addComponent(jbtnSupp))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
        //Recuperation des données concernant l'etablissement choisi à partir de son identifiant, afin de prechargé les champs de modifs
        //Enregistrement de la modif dans la bdd, puis rechargement du tableau afin de pouvoir afficher les modifs
    private void jbtnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifActionPerformed
        Byte bType = 3;
        String sReq = "from Etablissement Where Eta_Id = ?";
        Query q = jfPrincipal.getSession().createQuery(sReq);
        q.setParameter(0, jtxtid.getText());
            Etablissement unEtablissement = (Etablissement) q.uniqueResult();
            unEtablissement.setEtaNom(jtxtnom.getText());
            unEtablissement.setEtaRue(jtxtadresse.getText());
            unEtablissement.setEtaCp(jtxtcp.getText());
            unEtablissement.setEtaVille(jtxtville.getText());
            unEtablissement.setEtaTel(jtxttelephone.getText());
            unEtablissement.setEtaMail(jtxtmail.getText());

         
           if(jcbctype.getSelectedItem().toString() == "Ecole Publique")
            {
                bType = 0;
            }
           else if(jcbctype.getSelectedItem().toString() == "Ecole Privée")
            {
                bType = 1;
            }
           else if(jcbctype.getSelectedItem().toString() == "Autres")
            {
                bType = 2;
            }
          
           
           unEtablissement.setEtaType(bType);
           unEtablissement.setEtaNomresp(jtxtrespnom.getText());
           unEtablissement.setEtaPrenomresp(jtxtrespprenom.getText());
           unEtablissement.setEtaCivilresp(jcbccivil.getSelectedItem().toString());
           Transaction tx = jfPrincipal.getSession().beginTransaction();
           tx.commit();
           jfPrincipal.getSession().update (unEtablissement);
           chargerTable();
       
    }//GEN-LAST:event_jbtnModifActionPerformed
        //Permet de recuperer l'identifiant de la ligne selectionnée
    private void tblconsultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblconsultMouseClicked
        int ligne = tblconsult.getSelectedRow();
        Object cellule = tblconsult.getValueAt(ligne,0);
        chargerChamps(cellule);
        
                // TODO add your handling code here:
    }//GEN-LAST:event_tblconsultMouseClicked
        //Suppresion de l'etablissement selectionné / Rechargement du table afin de ne plus afficher l'etablissement supprimé 
    private void jbtnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuppActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Etes-vous sûr de vouloir supprimer ?", "Suppression",dialogButton);
            if(dialogResult==0)
            {
                String sReq = "FROM Etablissement WHERE eta_id = ?";
                Query q = jfPrincipal.getSession().createQuery(sReq);
                q.setParameter(0, jtxtid.getText());
                Etablissement unEtablissement = (Etablissement) q.uniqueResult();
                jfPrincipal.getSession().delete(unEtablissement);
                Transaction tx = jfPrincipal.getSession().beginTransaction();
                tx.commit();
                jfPrincipal.getSession().update(unEtablissement);
                chargerTable();  
            }
            else
            {

            }
              // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSuppActionPerformed
        //Permet de charger les champs lorsque l'on a selectionné un etablissement
    private void chargerChamps(Object cellule){
        String sReq = "From Etablissement Where Eta_Id = ?";
        Query q = jfPrincipal.getSession().createQuery(sReq);
        q.setParameter(0, cellule);
        Etablissement unEtablissement = (Etablissement) q.uniqueResult();
        jtxtid.setText(unEtablissement.getEtaId());
        jtxtnom.setText(unEtablissement.getEtaNom());
        jtxtadresse.setText(unEtablissement.getEtaRue());
        jtxtcp.setText(unEtablissement.getEtaCp());
        jtxtville.setText(unEtablissement.getEtaVille());
        jtxttelephone.setText(unEtablissement.getEtaTel());
        jtxtmail.setText(unEtablissement.getEtaMail());
        jtxtrespnom.setText(unEtablissement.getEtaNomresp());
        jtxtrespprenom.setText(unEtablissement.getEtaPrenomresp());
        jtxtcivil.setText(unEtablissement.getEtaCivilresp());
        Byte bType = unEtablissement.getEtaType();
        String sType = "";
        if(bType == 0)
            {
                sType = "Ecole publique";
            }
           else if(bType == 1)
            {
                 sType = "Ecole privée";
            }
           else if(bType == 2)
            {
                  sType = "Autres";
            }
        jtxttype.setText(sType);
    }
        //Permet de charger les etablissements dans le tableau
    public void chargerTable(){ 
       int iNbligne;
       int i;
       iNbligne = tblconsult.getRowCount();
        if(iNbligne > 0){
            for(i=0;i <iNbligne; i++){
                ((DefaultTableModel)tblconsult.getModel()).removeRow(0);
            }
        String sReq = "FROM Etablissement";
        
        Query q = jfPrincipal.getSession().createQuery(sReq);
        Iterator eta = q.iterate();
        while(eta.hasNext()){
            Etablissement unEtablissement = (Etablissement) eta.next();
            ((DefaultTableModel) tblconsult.getModel()).addRow(new Object[] {unEtablissement.getEtaId(), unEtablissement.getEtaNom(), unEtablissement.getEtaVille(), unEtablissement.getEtaType()});

        }   
        }
        
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnModif;
    private javax.swing.JButton jbtnSupp;
    private javax.swing.JComboBox jcbccivil;
    private javax.swing.JComboBox jcbctype;
    private javax.swing.JTextField jtxtadresse;
    private javax.swing.JTextField jtxtcivil;
    private javax.swing.JTextField jtxtcp;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtmail;
    private javax.swing.JTextField jtxtnom;
    private javax.swing.JTextField jtxtrespnom;
    private javax.swing.JTextField jtxtrespprenom;
    private javax.swing.JTextField jtxttelephone;
    private javax.swing.JTextField jtxttype;
    private javax.swing.JTextField jtxtville;
    private javax.swing.JLabel lbladresse;
    private javax.swing.JLabel lblconsult;
    private javax.swing.JLabel lblcp;
    private javax.swing.JLabel lbletablissement;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblrespnom;
    private javax.swing.JLabel lblrespnom1;
    private javax.swing.JLabel lblresponsable;
    private javax.swing.JLabel lblrespprenom;
    private javax.swing.JLabel lbltelephone;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lblville;
    private javax.swing.JTable tblconsult;
    // End of variables declaration//GEN-END:variables
}
